saving fingerprint to temp file than passing to inputs (#5)
# Why

having the error from integration https://github.com/expo/expo/pull/40257

```
Error: An error occurred trying to start process '/home/runner/actions-runner/cached/externals/node20/bin/node' with working directory '/home/runner/work/expo/expo'. Argument list too long
```

# How

it turns out passing full fingerprint as inputs/outputs between the composite actions doesn't work. this pr tries to save fingerprint into a `fingerprint-state-output-file` so that each action can load from that